theme = "blowfish"
baseURL = "https://xuzhang0112.github.io/"
languageCode = "en"
colorScheme = "blowfish"



[outputs]
home = ["HTML", "RSS", "JSON"]
[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

googleAnalytics = "G-MEASUREMENT_ID"

[taxonomies]
Tags = "Tags"
Year = "Year"
Conference = "Conference"
